name = "Ising"
uuid = "a4b17d44-13d4-4c91-98cd-0449bec393fd"
version = "0.1.1"
authors = ["Lukas Weber"]

[deps]
Carlo = "780c37f4-4e5a-43de-9e79-65c261e525a4"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Carlo = "0.3"
HDF5 = "0.17.2"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StaticArrays", "DataFrames", "Measurements"]
